package exception;

public class Arithmetic {
	public static void main(String args[]) {
		try {
			int num1=20;
		
		int num2=0;
		}
		catch(ArithmeticException Ae) {
			Ae.printStackTrace();
		}
		System.out.println("program ended");
	}
	
}
